version: "3.9"
networks:
  roboshop:
    driver: bridge
volumes:
  mysql:
    driver: local
    driver_opts:
          o: bind
          type: none
          device: /home/ec2-user/mysql
  redis:
    driver: local
    driver_opts:
          o: bind
          type: none
          device: /home/ec2-user/redis
  mongodb:
    driver: local
    driver_opts:
          o: bind
          type: none
          device: /home/ec2-user/mongodb
  rabbitmq:
    driver: local
    driver_opts:
          o: bind
          type: none
          device: /home/ec2-user/rabbitmq
services:
  mongodb:
   image: araguntajyothi/mongodb:v1
   container_name: mongodb
   volumes:
     - mongodb:/data/db
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis:/data
  mysql:
   image: araguntajyothi/mysql:v1
   container_name: mysql
   volumes:
     - mysql:/var/lib/mysql
  rabbitmq:
   image: rabbitmq
   container_name: rabbitmq
   volumes:
     - rabbitmq:/var/lib/rabbitmq
  catalogue:
    image: araguntajyothi/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  web:
    image: araguntajyothi/web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
      - ratings
  user:
   image: araguntajyothi/user:v1
   container_name: user
   depends_on:
     - mongodb
     - redis
  cart:
   image: araguntajyothi/cart:v2
   container_name: cart
   depends_on:
     - redis
     - catalogue
  shipping:
   image: araguntajyothi/shipping:v1
   container_name: shipping
   depends_on:
     - mysql
  payment:
   image: araguntajyothi/payment:v1
   container_name: payment
   depends_on:
     - rabbitmq
  ratings:
   image: araguntajyothi/ratings:v1
   container_name: ratings
   depends_on:
     - mysql